### PR TITLE
Stock XP System

### PR DESCRIPTION
**Pull request by Ippo343**
Also includes small changes due to KSP 1.0, namely:

- the temperatures are now measured in Kelvin
- the gimbal module has a different API now: I chose to completely remove the module, which also causes the gimbal to get stuck in place instead of going back to neutral ( 3:) )
- edited all the MM patches to use the stock XP system

### CODE REVIEW

**Comment by 602p** [comment]
@Ippo343 I've haven't been able to get this to work. Somewhere between loading it and the part being activated in flight the ExperienceRequirements gets reset to ('',0)

Not really sure why the EXPERIENCE node gets deleted. I think it would probably be easier to move the config out of the EXPERIENCE node and into the root level of the MODULE node, unless there is something obvious I'm missing.

**Comment by 602p** [comment]
Unless you have an objection, I'm just going to switch to using normal properties instead of a Node. I'll also be out of town this weekend so you might want to go ahead with the launch without me (or I can do it on Monday.)

**Comment by 602p** [comment]
I'll go over all the configs and change the experience placement.

**Comment by 602p** [comment]
At this point I'm gonna leave you to push this out, because I've really gotta study for the APUSH test!

Alternatively, I can probably do it Friday afternoon.

**Comment by 602p** [comment]
Alrighty @Ippo343 looks like we're ready to rumble.

I can upload a build to KerbalStuff/Github/KSP Forums. Just want to get your permission before we go ahead!

**Comment by Ippo343** [comment]
Hey Louis, I am currently on a business trip and won't be able to check it out for a couple of days, so it's your call :)

<div>-------- Messaggio originale --------</div><div>Da: Louis Goessling <notifications@github.com> </div><div>Data:08/05/2015  00:28  (GMT+01:00) </div><div>A: Ippo343/DangIt <DangIt@noreply.github.com> </div><div>Cc: Michele <m.ippolito@outlook.com> </div><div>Oggetto: Re: [DangIt] Stock XP System (#105) </div><div>
</div>
Alrighty @Ippo343 looks like we're ready to rumble.

I can upload a build to KerbalStuff/Github/KSP Forums. Just want to get your permission before we go ahead!


---

**Comment by 602p** [comment]
Alright, I'm gonna release it then.

Done some testing and it looks like it is still stable, so I'll go ahead and push out 0.6.

**Pull request merged**
